name: Data maker

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '0 3 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check-out this repo
      uses: actions/checkout@v2
    - name: Check website accessibilty
      run: |
        wget https://app2.controlenamao.com.br
        cat index.html
        rm index.html
    - name: Remove Chrome
      run: sudo apt purge google-chrome-stable
      
    - name: Remove default Chromium
      run: sudo apt purge chromium-browser
      
    - name: Install a new Chromium
      run: sudo apt install -y chromium-browser

    - name: Check Chromium present
      run: |
        which chromium-browser
        which chromium
    
    - name: Prepare environment
      run: |
        echo "Checking for old files"
        ls -a -l
        echo "Installing python libraries"
        python3 -m pip install selenium webdriver-manager

    - name: Run scrapper
      run: |
        echo "Running script"
        python3 scrapper_minimal.py ${{ secrets.APP_KEY }} ${{ secrets.APP_lOGIN}}

    - name: Check downloaded files
      run: ls -a -l
