name: Data maker

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '0 3 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check-out this repo
      uses: actions/checkout@v2
    
    - name: Prepare environment
      run: |
        echo "Checking for old files"
        ls -a -l
        echo "Installing python libraries"
        python3 -m pip install selenium

    - name: Run scrapper
      run: |
        echo "Running script"
        python3 scrapper_minimal.py ${{ secrets.APP_KEY }} ${{ secrets.APP_lOGIN}}
        echo "Checking files"
        ls -a -l
