name: Test

on:

  workflow_dispatch:

  
  
jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Test2
      if: always()
      run: which chrome

    - name: Test3
      if: always()
      run: which chromium-browser

    - name: Test4
      if: always()
      run: which chromium
        
    - name: Test
      if: always()
      run: |
        apt list --all-versions python3 chromium-browser chrome selenium
        apt list --all-versions chromium-browser
