name: Test

on:

  workflow_dispatch:

  
  
jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Test
      run: apt list --all-versions python3 chrome
    - name: Test2
      run: dpkg -l chromium
